import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  containerMonCre: {
    flex: 1,
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  languageLabel: {
    fontSize: 16,
    color: 'white',
    marginLeft: 10,
  },
  largeButton: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    backgroundColor: '#444',
    borderRadius: 8,
    marginHorizontal: 5,
  },
  largeButtonMonCre: {
    position: 'absolute',
    borderRadius: 8,
    top: -28,
    right: -180,
    alignItems: 'center',
    width: '30%',
    borderColor: '#0f101a',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
  },
  titleSesDet: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  descriptionSesDet: {
    fontSize: 18,
    marginBottom: 20,
    textAlign: 'center',
  },
  sessionsListSesDet: {
    width: '100%',
    marginVertical: 20,
  },
  sessionTabSesDet: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginVertical: 5,
    width: '100%',
  },
  sectionTitleSesDet: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  sessionTabTextSesDet: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  notesContainerSesDet: {
    width: '100%',
  },
  noteContainerSesDet: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 10,
    padding: 15,
    marginVertical: 5,
  },
  noteTitleSesDet: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  noteContentSesDet: {
    fontSize: 16,
  },
  noteImageSesDet: {
    width: '100%',
    height: 200,
    resizeMode: 'contain',
    borderRadius: 10,
    marginTop: 10,
  },
  sessionDescription: {
    fontSize: 14,
    color: '#ccc'
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  containerCamp: {
    flex: 1,
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  containerReg: {
    flex: 1,
    justifyContent: 'center',
//    alignItems: 'center',
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  appName: {
    position: 'absolute',
    top: '16%',
    fontSize: 30,
    textShadowColor: 'rgba(0, 0, 0, 0.7)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 3,
    fontWeight: 'bold',
  },
  CampName: {
    textAlign: 'center',
    fontSize: 24,
    color: '#7F7F7F',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  button: {
    alignItems: 'center',
    width: '100%',
  },
  buttonContainerUsu: {
    position: 'absolute',
    width: '60%',
    borderColor: 'rgba(60, 60, 60, 0.5)',
    borderRadius: 10,
    borderWidth: 2,
    shadowColor: 'rgba(0, 0, 0, 1)',
  },
  buttonBackground: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingVertical: 10,
    borderRadius: 10,
    overflow: 'hidden',
  },
  buttonText: {
    color: '#ffd700',
    fontSize: 20,
    textShadowColor: 'black',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
    fontStyle: 'italic',
    flex: 1,
    textAlign: 'center',
  },
  twoColumnContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  column: {
    flex: 1,
    marginHorizontal: 5,
  },
  columnSpells: {
    flex: 1,
    minWidth: 150,
  },
  columnTop: {
    flex: 1,
    marginHorizontal: 35,
  },
  columnAdding: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 10,
    width: '100%',
    marginVertical: 5,
  },
  labelMonCre: {
    fontSize: 16,
    color: 'white',
    marginVertical: 5,
    marginBottom: 5,
  },
  labelMonCreHitPoint: {
    fontSize: 16,
    color: 'blue',
  },
  checkboxContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  checkboxContainer1: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  labelMonstrum: {
    textAlign: 'center',
    color: '#d6d6d6',
    fontSize: 16,
    marginBottom: 5,
    marginRight: 10,
  },
  buttonTextCharacter: {
    fontSize: 16,
    color: '#d6d6d6',
  },
  buttonTextCamp: {
    fontSize: 16,
    color: '#d6d6d6',
  },
  icons: {
    marginRight: -30,
    marginLeft: 10,
    width: 40,
    height: 40,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContainerMonCre: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContentMonCre: {
    width: '80%',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
  },
  modalTitleMonCre: {
    fontSize: 18,
    marginBottom: 10,
    textAlign: 'center',
  },
  columnDescr: {
    alignItems: 'right',
  },
  TextMonCre: {
    backgroundColor: '#f0f0f0',
    height: 'auto',
    alignSelf: 'flex-start',
    borderRadius: 10,
    textAlignVertical: 'top',
  },
  modalInputMonCre: {
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    padding: 10,
    height: 100,
    textAlignVertical: 'top',
    marginBottom: 20,
  },
  modalInputMonCreHitPoints: {
    backgroundColor: '#f0f0f0',
  },
  modalTitle: {
    fontSize: 22,
    color: '#d6d6d6',
    marginBottom: 10,
  },
  modalButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#444',
    marginVertical: 10,
    width: '100%',
    borderRadius: 10,
  },
  modalCloseButton: {
    marginTop: 20,
  },
  modalCloseButtonText: {
    color: '#d6d6d6',
    fontSize: 16,
  },
  scrollContainer: {
    paddingTop: '20%',
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  scrollContainerCamp: {
    paddingTop: '40%',
    paddingHorizontal: 40,
  },
  scrollContainerRzut: {
    alignItems: 'center',
    paddingTop: '40%',
    paddingHorizontal: 35,
    paddingBottom: 40,
  },
  sessionContainer: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  sessionName: {
    color: '#d6d6d6',
    fontSize: 18,
  },
  sessionContent: {
    color: '#d6d6d6',
    marginTop: 10,
  },
  sessionsList: {
    textAlign: 'center',
    top: '10%',
    width: '100%',
    borderColor: '#7F7F7F',
    borderBottomWidth: 1.5,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    zIndex: 1,
  },
  sessionTab: {
    padding: 10,
    borderColor: '#7F7F7F',
    borderRightWidth: 1.5,
  },
  sessionTabText: {
    color: '#d6d6d6',
    fontSize: 18,
  },
  editTextCamp: {
    color: 'yellow',
    marginHorizontal: 5,
  },
  EditText: {
    fontSize: 10,
    color: '#d6d6d6',
  },
  editText: {
    color: '#d6d6d6',
    marginHorizontal: 5,
  },
  deleteTextCamp: {
    color: 'red',
    marginHorizontal: 5,
  },
  deleteText: {
    color: '#d6d6d6',
    marginHorizontal: 5,
  },
  newNoteContainer: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  inputCampNote: {
    borderColor: '#7F7F7F',
    color: '#d6d6d6',
    borderWidth: 1.5,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  input: {
    width: '100%',
    padding: 10,
    borderColor: '#fff',
    borderWidth: 1,
    borderRadius: 5,
    color: '#fff',
    marginVertical: 10,
  },
  inputMonCre: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
    marginLeft: 0,
  },
  inputMonCreStat: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
    marginHorizontal: 70,
    marginLeft: 0,
  },
  inputInventory: {
    borderBottomWidth: 1,
    marginBottom: 10,
    padding: 8,
  },
  inputNotes: {
    width: '100%',
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    color: '#d6d6d6',
    paddingHorizontal: 10,
    marginRight: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  inputCamp: {
    width: '70%',
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    color: '#d6d6d6',
    paddingHorizontal: 10,
    marginRight: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  contentInput: {
    color: '#d6d6d6',
    marginTop: 10,
    marginBottom: 10,
  },
  noteHeader: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 5,
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  noteActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  noteImage: {
    marginTop: 10,
    width: 350,
    height: 350,
  },
  noteTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#9F9F9F',
  },
  noteContent: {
    fontSize: 16,
    color: '#8F8F8F',
    marginTop: 10,
  },
  shareText: {
    color: 'green',
    marginHorizontal: 15,
  },
  saveButton: {
    alignItems: 'center',
  },
  saveText: {
    color: 'green',
    fontSize: 16,
  },
  picker: {
    height: 50,
    width: '101%',
    color: '#d6d6d6',
    backgroundColor: '#fff',
  },
  pickerChooseChar: {
    width: '101%',
    color: '#d6d6d6',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  pickerMonCre: {
    color: 'black',
    backgroundColor: '#fff',
    marginVertical: 3,
  },
  addButtonMonCre: {
    backgroundColor: '#ffa500',
    padding: 10,
    borderRadius: 8,
    width: "40%",
    alignItems: 'right',
  },
  imagePicker: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  imagePickerText: {
    color: 'yellow',
    fontSize: 16,
  },
  addButtonTextCamp: {
    color: 'green',
    fontSize: 16,
    textAlign: 'center',
  },
  addButtonText: {
    color: 'white',
    fontSize: 16,
  },
  autoAddButtonText: {
    color: 'white',
    fontSize: 16,
  },
  newNoteImage: {
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
  },
  cancelButton: {
    marginTop: 10,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: 'red',
  },
  deleteButtonCamp: {
    alignItems: 'center',
    color: 'red',
    fontSize: 16,
  },
  newSessionContainer: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  inputName: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    color: '#d6d6d6',
    paddingHorizontal: 10,
    marginTop: 10,
    marginBottom: 10,
  },
  inputContent: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    color: '#d6d6d6',
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  textArea: {
    height: 100,
  },
  addButton: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  addButton: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: 'center',
  },
  addButton: {
    marginTop: 10,
    padding: 10,
    backgroundColor: '#2d2d38',
    borderRadius: 5,
  },
  addButtonInventory: {
    padding: 10,
    backgroundColor: 'green',
    borderRadius: 5,
    alignItems: 'center',
  },
  autoAddButton: {
    padding: 10,
    backgroundColor: 'blue',
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 10,
  },
  chainOverlay: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: 0,
    left: 0,
  },
  addButtonImage: {
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    padding: 10,
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
    paddingHorizontal: 40,
    borderColor: '#7F7F7F',
  },
  addButtonCamp: {
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    alignItems: 'center',
  },
  playerPanel: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderTopColor: '#7F7F7F',
    borderTopWidth: 1.5,
    padding: 10,
  },
  playerAvatar: {
    margin: 5,
    padding: 5,
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 50,
  },
  playerImage: {
    width: 50,
    height: 50,
    borderRadius: 50,
  },
  selectedPlayer: {
    borderColor: 'yellow',
  },
  addPlayerText: {
    color: '#d6d6d6',
    fontSize: 18,
    top: 10,
    paddingHorizontal: 20,
  },
  playerActions: {
    bottom: 90,
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    padding: 5,
    borderTopColor: '#7F7F7F',
    borderTopWidth: 1,
  },
  playerActionButton: {
    padding: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderRadius: 50,
  },
  actionText: {
    color: '#d6d6d6',
    textAlign: "center",
  },
  playerActionText: {
    color: '#d6d6d6',
  },
  dropdownContainer: {
    position: 'absolute',
    top: '3%',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 1)',
    width: '40%',
  },
  blackLeftContainer: {
    backgroundColor: 'rgba(0, 0, 0, 1)',
    borderColor: '#7F7F7F',
    borderWidth: 1,
  },
  statsContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  statBox: {
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 1.0)',
    borderColor: '#7F7F7F',
    borderWidth: 1,
    alignItems: 'center',
  },
  largeText: {
    fontSize: 24,
    color: '#d6d6d6',
    marginBottom: 5,
  },
  statText: {
    color: '#d6d6d6',
  },
  circleBox: {
    width: 70,
    height: 70,
    borderRadius: 100,
    backgroundColor: 'rgba(0, 0, 0, 1)',
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleText: {
    fontSize: 24,
    color: '#ffffff',
  },
  circleLabel: {
    marginBottom: 10,
    fontSize: 12,
    color: '#d6d6d6',
  },
  imageContainer: {
    position: 'absolute',
    top: '10%',
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: 100,
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    overflow: 'hidden',
  },
  healthContainer: {
    position: 'absolute',
    top: '19%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  healthBar: {
    width: '120%',
    height: 15,
    backgroundColor: '#555',
    borderRadius: 10,
    overflow: 'hidden',
    marginVertical: 10,
  },
  healthText: {
    color: 'green',
  },
  damageText: {
    color: 'red',
  },
  healthFill: {
    height: '100%',
    backgroundColor: 'red',
  },
  healthButton: {
    backgroundColor: 'rgba(0, 0, 0, 1)',
    color: 'green',
    padding: 10,
    right: 90,
    bottom: 60,
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    width: 75,
    height: 50,
    alignItems: 'center',
  },
  damageButton: {
    backgroundColor: 'rgba(0, 0, 0, 1)',
    padding: 10,
    left: 90,
    bottom: 110,
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    width: 75,
    height: 50,
    alignItems: 'center',
  },
  EditBox: {
    marginTop: 25,
    padding: 10,
    width: 70,
    backgroundColor: 'rgba(0, 0, 0, 1.0)',
    borderColor: '#7F7F7F',
    borderWidth: 1,
    alignItems: 'center',
  },
  Skills: {
    position: 'absolute',
    right: 0,
    top: 0,
    padding: 25,
    backgroundColor: 'rgba(0, 0, 0, 1)',
    borderColor: '#7F7F7F',
    borderWidth: 1,
    alignItems: 'center',
  },
  SkillsText: {
    fontSize: 20,
    color: '#d6d6d6',
  },
  skillsWindow: {
    position: 'absolute',
    top: '25%',
    left: '10%',
    right: '10%',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 10,
    padding: 30,
    zIndex: 1,
  },
  skillRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  circle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginRight: 10,
  },
  skillMod: {
    width: 50,
  },
  skillName: {
    flex: 1,
  },
  skillBonus: {
    width: 50,
    textAlign: 'center',
  },
  bonusBox: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
    padding: 1,
    marginRight: 10,
  },
  headerText: {
    width: 50,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  headerTextCamp: {
    marginBottom: 20,
    fontSize: 24,
    color: '#7F7F7F',
    textAlign: 'center',
  },
  rightContainer: {
    position: 'absolute',
    top: '10%',
    right: 0,
    height: '70%',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderColor: '#7F7F7F',
    borderWidth: 2,
  },
  rightButton: {
    padding: 10,
    paddingBottom: 15,
    backgroundColor: 'rgba(0, 0, 0, 1.0)',
    borderColor: '#7F7F7F',
    borderWidth: 1,
    alignItems: 'center',
  },
  abilityWindow: {
    position: 'absolute',
    top: '25%',
    backgroundColor: '#000',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#7F7F7F',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  skillsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  pickerItemsContainer: {
    flexDirection: 'row',
  },
  pickerItems: {
    width: "30%",
    backgroundColor: '#2d2d38',
    color: "#d6d6d6",
  },
  abilityImage: {
    width: 40,
    height: 40,
    marginHorizontal: 5,
  },
  powerLevels: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 10,
  },
  diceTurnContainer: {
    position: 'absolute',
    bottom: 10,
    left: '40%',
    width: '100%',
    alignItems: 'center',
  },
  TurnDiceButton: {
    width: 70,
    height: 70,
    borderRadius: 100,
    backgroundColor: 'rgba(0, 0, 0, 1)',
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rightTurnDiceText: {
    fontSize: 14,
    color: '#d6d6d6',
  },
  dropdownContainer: {
    position: 'absolute',
    top: '3%',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 1)',
    width: '40%',
  },
  characterRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  characterImage: {
    width: 100,
    height: 100,
    margin: 10,
    justifyContent: 'flex-end',
  },
    characterStatus: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 5,
    textAlign: 'center',
  },

  ConButtonCharacter: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 10,
    width: '40%',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#7F7F7F',
    alignItems: 'center',
  },
  ConButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 10,
    width: '60%',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#7F7F7F',
    alignItems: 'center',
  },
  ConButtonNotes: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 10,
    width: '60%',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#7F7F7F',
    alignItems: 'center',
    marginTop: 15,
  },
  ConButtonText: {
    color: '#d6d6d6',
    fontSize: 20,
  },
  RaceGenderPosCont: {
    marginTop: 20,
    marginBottom: 10,
    alignItems: 'flex-start',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 5,
  },
  RaceGenderPosContTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 10,
  },
  RaceGenderTitle: {
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    color: '#f0f0f0',
    fontSize: 20,
    fontWeight: 'bold',
  },
  selectedClassInfo: {
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    color: '#f0f0f0',
    fontSize: 20,
    fontWeight: 'bold',
  },
  textInput: {
    height: 40,
    width: 200,
    backgroundColor: '#f0f0f0',
    borderRadius: 5,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  pickerCharacter: {
    height: 40,
    width: 200,
    backgroundColor: '#f0f0f0',
    borderRadius: 5,
  },
  selectedImageContainer: {
    marginTop: 70,
    position: 'center',
  },
  selectedImageCharacter: {
    width: 250,
    height: 250,
    marginTop: '-15%',
    marginBottom: '10%',
    resizeMode: 'contain',
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nicknameContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 10,
    borderRadius: 5,
  },
  nicknameText: {
    color: '#FFD700',
    fontSize: 24,
    fontWeight: 'bold',
  },
  diceResult: {
    fontSize: 18,
    color: '#d9534f',
    marginVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 1)',
  },
  selectedImage: {
    width: 400,
    height: 400,
    resizeMode: 'contain',
  },
  remainingPointsText: {
    backgroundColor: 'rgba(0,0,0,0.8)',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  itemModal: {
    width: '90%',
    backgroundColor: '#1c1c1e',
    borderRadius: 8,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  SpellModal: {
    width: '90%',
    overflow: 'hidden',
    backgroundColor: '#1c1c1e',
    borderRadius: 8,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  itemMagicModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  itemTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
    textAlign: 'center',
  },
  attributeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  attributeText: {
    color: '#7F7F7F',
    fontSize: 20,
    fontWeight: 'bold',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
  },
  modalOverlayItems: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalContentCharacter: {
    backgroundColor: '#7F7F7F',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  modalContentDMBook: {
    width: '60%',
    backgroundColor: 'rgba(0,0,0,0.8)',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  modalContent: {
    padding: 20,
    alignItems: 'center',
  },
  modalContentSpells: {
    width: '80%',
    padding: 20,
    backgroundColor: '#333',
    borderRadius: 10,
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalContentInventory: {
    width: '80%',
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  modalOption: {
    fontSize: 18,
    padding: 10,
    textAlign: 'center',
  },
  blockTitle: {
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#d6d6d6',
    marginTop: 20,
    marginBottom: 5,
  },
  blockContent: {
    width: '90%',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    padding: 20,
    borderRadius: 10,
  },
  pickerCharacter3: {
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  inputCharacter: {
    height: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderColor: 'grey',
    borderWidth: 2,
    marginBottom: 20,
    paddingLeft: 10,
  },
  content: {
    padding: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 10,
  },
  title: {
    fontSize: 24,
    color: '#d6d6d6',
    marginBottom: 10,
  },
  titleSelect: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#d6d6d6',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    width: '100%',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    color: '#d6d6d6',
    marginTop: 10,
  },
  goldInputContainer: {
    marginTop: 10,
  },
  IteminputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  goldInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  goldInput: {
    width: 100,
    height: 40,
    backgroundColor: '#d6d6d6',
    marginLeft: 10,
    borderRadius: 5,
    textAlign: 'center',
    fontSize: 16,
    padding: 5,
  },
  totalGold: {
    fontSize: 20,
    color: '#FFD700',
    marginTop: 20,
    textAlign: 'center',
  },

    message: {
      position: 'absolute',
      top: '41%',
      textAlign: 'center',
      fontSize: 16,
      color: '#d6d6d6',
      width: '80%',
    },
    okButton: {
      position: 'absolute',
      backgroundColor: 'transparent',
      borderRadius: 10,
      paddingVertical: 15,
      paddingHorizontal: 50,
      alignItems: 'center',
      bottom: '40%',
    },
    okButtonText: {
      color: '#d6d6d6',
      fontSize: 20,
      fontWeight: 'bold',
    },
  searchInput: {
    marginTop: 100,
    width: '80%',
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    padding: 10,
    color: '#d6d6d6',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  filterContainerItemMon: {
    width: '80%',
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filterContainer: {
    width: '80%',
    marginTop: 20,
  },
  filterToggle: {
    backgroundColor: '#444',
    padding: 3,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '30%',
  },
  filterToggleText: {
    color: '#d6d6d6',
    fontSize: 16,
  },
  activeFilterToggle: {
    backgroundColor: '#777',
  },
  filterOptionsContainer: {
    width: '90%',
    marginTop: 10,
    marginBottom: -200,
  },
  filterBlock: {
    marginBottom: 15,
  },
  filterOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  filterButton: {
    padding: 10,
    marginHorizontal: 5,
    backgroundColor: '#444',
    borderRadius: 10,
  },
  selectedFilterButton: {
    backgroundColor: '#777',
  },
  filterButtonText: {
    color: '#d6d6d6',
  },
  monsterContainer: {
    width: '80%',
    marginTop: 20,
  },
  monsterItem: {
    backgroundColor: '#333',
    padding: 15,
    marginVertical: 10,
    borderRadius: 10,
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
  },
  monsterName: {
    fontSize: 18,
    color: '#d6d6d6',
  },
  monsterDetails: {
    color: '#a1a1a1',
  },
  noResultsText: {
    color: '#d6d6d6',
    fontSize: 18,
  },
    resetPass: {
      color: '#d6d6d6',
      fontSize: 22,
    },
    separator: {
      position: 'absolute',
      top: '35%',
      left: '10%',
      flexDirection: 'row',
      alignItems: 'center',
    },
    separatorLine: {
      flex: 3,
      height: 1,
      backgroundColor: 'grey',
      width: '200%',
    },
    email: {
      position: 'absolute',
      color: '#d6d6d6',
      left: '10%',
    },
    emailLabel: {
      position: 'absolute',
      color: '#d6d6d6',
      left: '10%',
      top: '40%',
    },
    emailInput: {
      position: 'absolute',
      backgroundColor: 'white',
      borderColor: '#d6d6d6',
      borderRadius: 4,
      paddingVertical: 0,
      paddingHorizontal: 8,
      fontSize: 16,
      width: '70%',
      top: '53%',
      left: '10%',
      marginBottom: 20,
    },
    sendEmail: {
      position: 'absolute',
      backgroundColor: 'transparent',
      borderRadius: 10,
      paddingVertical: 15,
      paddingHorizontal: 50,
      alignItems: 'center',
      top: '57%',
    },
    sendEmailText: {
      color: '#d6d6d6',
      fontSize: 16,
      fontWeight: 'bold',
    },
  flagsContainer: {
    position: 'absolute',
    top: 10,
    left: 10,
  },
  dropdown: {
    marginTop: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderRadius: 5,
    padding: 5,
    elevation: 5,
  },
  flagButton: {
    marginVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  flag: {
    width: 50,
    height: 30,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: '35%',
    width: '60%',
    borderColor: 'rgba(60, 60, 60, 0.5)',
    borderRadius: 10,
    borderWidth: 2,
    shadowColor: 'rgba(0, 0, 0, 1)',
  },
  buttonContainerMonCre: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginVertical: 10,
  },
  gearIcon: {
    width: 50,
    height: 50,
  },
  themeContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  themePreview: {
    width: 150,
    height: 300,
    marginRight: 10,
  },
  themeLabel: {
    color: 'white',
    fontSize: 20,
    marginTop: 8,
  },
  categoryContainer: {
    flexDirection: 'row',
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    maxHeight: 50,
  },
  categoryButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginHorizontal: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
  },
  selectedCategoryButton: {
    backgroundColor: 'rgba(160, 160, 160, 0.9)',
  },
  categoryButtonText: {
    color: 'white',
    fontSize: 14,
  },
  modalDescription: {
    color: '#aeafb5',
    fontSize: 16,
    marginVertical: 15,
    textAlign: 'center',
  },
  modalDetails: {
    fontSize: 14,
    color: '#aeafb5',
    marginBottom: 20,
  },
  modalDetailsSpells: {
    borderColor: 'rgba(60, 60, 60, 0.5)',
    borderWidth: 2,
    padding: 4.5,
    textAlign: 'center',
    alignItems: 'center',
    fontSize: 14,
    color: '#aeafb5',
  },
  modalDetailsSpellsSchool: {
    borderColor: 'rgba(60, 60, 60, 0.5)',
    borderWidth: 2,
    padding: 4.5,
    textAlign: 'center',
    alignItems: 'center',
    fontSize: 14,
  },
  modalTitleInv: {
    color: 'black',
    fontSize: 24,
    marginBottom: 20,
  },
  modalTitleFeats: {
    fontSize: 24,
    color: '#c5c6c9',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalSubTitleFeats: {
    fontSize: 18,
    textAlign: 'center',
    color: '#c5c6c9',
  },
  statsContainerFeats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statsContainerFeatsA: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 15,
  },
  statsContainerFeatsB: {
    justifyContent: 'space-around',
    borderWidth: 1,
    borderColor: '#444',
    padding: 10,
    backgroundColor: '#292929',
  },
  statBlock: {
    alignItems: 'center',
  },
  additionalInfo: {
    padding: 10,
    borderWidth: 1,
    borderColor: '#444',
    backgroundColor: '#292929',
  },
  additionalInfoTitle: {
    justifyContent: 'space-around',
    flex: 1,
    padding: 10,
    borderWidth: 1,
    borderColor: '#444',
    backgroundColor: '#292929',
  },
  actionName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#c5c6c9',
  },
  actionDescription: {
    fontSize: 14,
    color: '#c5c6c9',
  },
  featureName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#c5c6c9',
  },
  featureDescription: {
    fontSize: 14,
    color: '#c5c6c9',
  },
  sectionTitleFeats: {
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 15,
    marginBottom: 5,
  },
  modalDetailsFeats: {
    fontSize: 16,
    marginBottom: 5,
  },
  actionContainerFeats: {
    marginBottom: 10,
  },
  featureContainerFeats: {
    marginBottom: 10,
  },
  featsContainerColumn:{
    textAlign: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#444',
    backgroundColor: '#292929',
  },
  statCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 20,
  },
  statValue: {
    fontSize: 16,
    color: '#c5c6c9',
    fontWeight: 'bold',
  },
  statLabel: {
    fontSize: 12,
    color: '#c5c6c9',
  },
  featStatSmall: {
    fontSize: 12,
    color: '#c5c6c9',
  },
  modalImage: {
    width: '100%',
    height: 165,
    width: 165,
    borderRadius: 10,
  },
  modalContentFeats: {
    backgroundColor: '#333',
    borderRadius: 10,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
    overflow: 'hidden',
  },

  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoColumn: {
    flex: 1,
  },

  modalTitleSpells: {
    color: '#c5c6c9',
    fontSize: 24,
    textAlign: 'center',
  },
  themeOption: {
    alignItems: 'center',
    marginVertical: 10,
  },
  closeButton: {
    marginTop: 20,
    padding: 10,
  },
  closeButtonItem: {
    backgroundColor: '#444',
    borderRadius: 4,
    padding: 10,
    flex: 1,
    alignItems: 'center',
    marginRight: 8,
  },
  closeButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  editButton: {
    backgroundColor: '#1d9bf0',
    borderRadius: 4,
    padding: 10,
    flex: 1,
    alignItems: 'center',
  },
  editButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  dropdownContainerCharacter: {
    position: 'absolute',
    top: '3%',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
    borderRadius: 10,
    backgroundColor: 'black',
    width: '40%',
  },
  tableContainer: {
    width: '90%',
  },
  tableHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#2d2d38',
    padding: 4,
  },
  tableHeaderText: {
    color: '#d6d6d6',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  goldBar: {
    backgroundColor: '#ffd700',
    padding: 3,
    borderRadius: 5,
  },
  goldText: {
    fontWeight: 'bold',
    color: '#000',
  },
  nameColumn: {
    width: 70,
  },
  weightColumn: {
    width: 50,
  },
  quantityColumn: {
    width: 84,
  },
  costColumn: {
    width: 38,
  },
  actionsColumn: {
    width: 150,
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#3f3f4d',
    padding: 4,
    marginBottom: -1,
  },
  tableCell: {
    flex: 1,
    color: '#d6d6d6',
    borderBottomColor: '#04021f',
    borderBottomWidth: 1,
    textAlign: 'center',
  },
  removeButton: {
    marginBottom: 6,
    flex: 1,
    backgroundColor: '#a30b0b',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  descriptionButton: {
    marginBottom: 6,
    backgroundColor: 'green',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeButtonText: {
    color: 'red',
    textAlign: 'right',
  },
  removeButtonTextInvent: {
    color: 'white',
    textAlign: 'right',
  },
  descriptionButtonText: {
    color: '#fff',
    fontSize: 14,
  },
  summaryContainer: {
    marginLeft: 15,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  summaryTextRight: {
    marginLeft: 5,
    fontSize: 16,
    color: '#d6d6d6',
  },
  summaryTextLeft: {
    marginRight: 5,
    fontSize: 16,
    color: '#d6d6d6',
  },
  goBackContainer: {
    position: 'absolute',
    top: 42,
    left: 20,
    width: '20%',
    borderColor: '#7F7F7F',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
  },
  item: {
    backgroundColor: '#333',
    padding: 15,
    marginVertical: 10,
    borderRadius: 10,
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
  },
  itemContainer: {
    justifyContent: 'space-between',
    padding: 10,
    marginBottom: 2,
    backgroundColor: '#080917',
    width: "100%",
  },
  itemContainerItems: {
    flexDirection: 'row',
    padding: 10,
    marginBottom: 5,
  },
  itemName: {
    fontSize: 18,
    color: '#d6d6d6',
  },
  itemDetails: {
    color: '#a1a1a1',
  },
  itemCategory: {
    fontSize: 14,
    color: '#b5b5b5',
  },
  itemsDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  noResultsText: {
    color: '#d6d6d6',
    fontSize: 18,
  },
  cos: {
    color: '#d6d6d6',
    fontSize: 20,
    position: 'absolute',
    top: '50%',
  },
    cos: {
      color: '#d6d6d6',
      fontSize: 20,
      position: 'absolute',
      top: '50%',
    },
    cos: {
          color: '#d6d6d6',
          fontSize: 20,
          position: 'absolute',
          top: '50%',
        },
  GoBack: {
    position: 'absolute',
    top: '5%',
    left: '5%',
    width: '20%',
    borderColor: 'rgba(60, 60, 60, 0.5)',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
  },
  GoBackText: {
    color: '#d6d6d6',
  },
  titleLogin: {
    position: 'absolute',
    top: '25%',
    left: '10%',
    fontSize: 22,
    alignItems: 'center',
    fontWeight: 'bold',
    color: '#d6d6d6'
  },
  newUser: {
    position: 'absolute',
    top: '27%',
    left: '10%',
    alignItems: 'center',
    marginVertical: 10,
  },
  newUserText: {
    flex: 1,
    color: '#d6d6d6'
  },
  buttonUser: {
    paddingVertical: 0,
    paddingHorizontal: 8,
    width: '250%',
    flexDirection: 'row',
    position: 'absolute',
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderWidth: 1,
    borderColor: '#007bff',
    borderRadius: 4,
    left: '105%'
  },
  buttonUserText: {
    color: '#007bff',
    textAlign: 'left',
  },
  labelLogin: {
    position: 'absolute',
    top: '35%',
    left: '10%',
    fontSize: 16,
    color: '#d6d6d6'
  },
  labelPassword: {
    position: 'absolute',
    marginTop: '5%',
    left: '10%',
    fontSize: 16,
    color: '#d6d6d6'
  },
  inputLogin: {
    position: 'absolute',
    borderWidth: 1,
    backgroundColor: 'white',
    borderColor: '#d6d6d6',
    borderRadius: 4,
    top: '39%',
    left: '9%',
    paddingVertical: 0,
    paddingHorizontal: 8,
    marginBottom: 20,
    fontSize: 16,
    width: '60%',
    alignSelf: 'flex-start',
  },
  inputPassword: {
    position: 'absolute',
    borderWidth: 1,
    backgroundColor: 'white',
    borderColor: '#d6d6d6',
    top: '51%',
    borderRadius: 4,
    left: '9%',
    paddingVertical: 0,
    paddingHorizontal: 8,
    marginBottom: 20,
    fontSize: 16,
    width: '60%',
    alignSelf: 'flex-start',
  },
  forgotPasswordButtonText: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderWidth: 1,
    borderColor: '#007bff',
    paddingVertical: 0,
    paddingHorizontal: 8,
    borderRadius: 4,
    position: 'absolute',
    marginTop: 45,
    fontSize: 16,
    left: '-41%',
    color: '#007bff',
  },
  continueButton: {
    position: 'absolute',
    top: '58%',
    padding: 25,
    backgroundColor: 'transparent',
  },
  continueButtonText: {
    color: '#d6d6d6',
    fontSize: 18,
    fontWeight: 'bold',
  },
  separator: {
    position: 'absolute',
    top: '65%',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  separatorText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 16,
    color: '#d6d6d6',
  },
  separatorLine: {
    flex: 3,
    height: 1,
    backgroundColor: '#d6d6d6',
  },
  media: {
    position: 'absolute',
    top: '75%',
  },
  socialGoogle: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderColor: '#7F7F7F',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1.5,
  },
  socialFacebook: {
    backgroundColor: '#3b5998',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
  },
  socialApple: {
    backgroundColor: 'black',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
  },
  appleicon: {
    width: 20,
    height: 20,
    marginRight: 5,
  },
  facebookicon: {
    width: 20,
    height: 20,
    marginRight: 5,
  },
  googleicon: {
    width: 20,
    height: 20,
    marginRight: 5,
  },
  socialButtonText: {
    color: '#d6d6d6',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  emailContainer: {
   flexDirection: 'row',
   alignItems: 'center',
   marginBottom: 30,
   marginHorizontal: 10,
  },
 loginContainer: {
   flexDirection: 'row',
   alignItems: 'center',
   marginBottom: 30,
   marginHorizontal: 10,
  },
  passContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
    marginHorizontal: 10,
  },
  captchaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
    marginHorizontal: 10,
  },
  label: {
    color: '#d6d6d6',
    fontSize: 16,
    marginBottom: 5,
    marginRight: 10,
  },
  emailInput: {
    borderWidth: 1,
    backgroundColor: 'white',
    borderColor: '#d6d6d6',
    borderRadius: 4,
    paddingVertical: 0,
    paddingHorizontal: 8,
    marginBottom: 6,
    fontSize: 16,
    flex: 1,
  },
  loginInput: {
    borderWidth: 1,
    backgroundColor: 'white',
    borderColor: '#d6d6d6',
    borderRadius: 4,
    paddingVertical: 0,
    paddingHorizontal: 8,
    marginBottom: 6,
    fontSize: 16,
    flex: 1,
  },
  passInput: {
    borderWidth: 1,
    backgroundColor: 'white',
    borderColor: '#d6d6d6',
    borderRadius: 4,
    paddingVertical: 0,
    paddingHorizontal: 8,
    marginBottom: 6,
    fontSize: 16,
    flex: 1,
  },
  confirmPassInput: {
    borderWidth: 1,
    backgroundColor: 'white',
    borderColor: '#d6d6d6',
    borderRadius: 4,
    paddingVertical: 0,
    paddingHorizontal: 8,
    marginBottom: 6,
    fontSize: 16,
    flex: 1,
  },
  captchaInput: {
    borderWidth: 1,
    backgroundColor: 'white',
    borderColor: '#d6d6d6',
    borderRadius: 4,
    paddingVertical: 0,
    paddingHorizontal: 8,
    marginBottom: 6,
    fontSize: 16,
    flex: 1,
  },
  registerButton: {
    backgroundColor: 'transparent',
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 50,
    alignItems: 'center',
  },
  registerButtonText: {
    color: '#d6d6d6',
    fontSize: 20,
    fontWeight: 'bold',
  },
    message: {
      position: 'absolute',
      top: '41%',
      textAlign: 'center',
      fontSize: 16,
      color: '#d6d6d6',
      width: '80%',
    },
    okButton: {
      position: 'absolute',
      backgroundColor: 'transparent',
      borderRadius: 10,
      paddingVertical: 15,
      paddingHorizontal: 50,
      alignItems: 'center',
      bottom: '40%',
    },
    okButtonText: {
      color: '#d6d6d6',
      fontSize: 20,
      fontWeight: 'bold',
    },
  diceBar: {
    position: 'absolute',
    top: '10%',
    flexDirection: 'row',
    paddingHorizontal: 10,
  },
  diceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  diceContainerRzut: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 90,
    height: 90,
    marginHorizontal: 5,
    margin: 10,
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  selectedDice: {
    borderColor: '#FFD700',
    borderWidth: 2,
    borderRadius: 8,
  },
  dice: {
    width: 50,
    height: 50,
  },
  diceKostka: {
    width: 200,
    height: 200,
  },
  diceContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  diceValue: {
    position: 'absolute',
    fontSize: 33,
    fontWeight: 'bold',
    color: '#d6d6d6',
  },
  diceRzut: {
    width: 65,
    height: 65,
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  counterButton: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7F7F7F',
    borderRadius: 5,
  },
  counterText: {
    color: '#fff',
  },
  counterValue: {
    marginHorizontal: 8,
    fontSize: 18,
    color: 'black',
  },
  buttonContainerRzut: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  rollButton: {
    marginTop: 20,
    borderRadius: 8,
    backgroundColor: 'goldenrod',
    paddingVertical: 10,
    paddingHorizontal: 30,
  },
  rollButtonText: {
    fontSize: 20,
    color: 'black',
  },
  resetButton: {
    paddingVertical: 10,
    backgroundColor: 'crimson',
    borderRadius: 8,
    marginHorizontal: 10,
    marginTop: 20,
    paddingHorizontal: 20,
  },
  resetButtonText: {
    fontSize: 20,
    color: 'black',
  },
  resultsContainer: {
    marginTop: 20,
  },
  resultContainer: {
    marginVertical: 5,
    padding: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 10,
  },
  resultText: {
    fontSize: 18,
    color: 'black',
  },
  resultTextKostka: {
    fontSize: 26,
    color: '#7F7F7F',
  },
  invItemDescription: {
    color: 'blue',
  },
  itemDescription: {
    fontSize: 14,
    color: '#fff',
    marginBottom: 12,
  },
  itemDescriptionSpell: {
    fontSize: 14,
    color: '#fff',
    marginTop: 20,
    marginBottom: 12,
  },
  itemDescriptionAttune: {
    textAlign: "center",
    fontSize: 14,
    color: '#fff',
    marginBottom: 12,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  selectionContainer: {
    flex: 1,
    flexDirection: 'row',
  },
  optionContainer: {
    flex: 1,
  },
  option: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#d6d6d6',
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 99)',
    width: '100%',
    textAlign: 'center',
  },
  playericon: {
    width: '100%',
    height: '100%',
  },
  dmicon: {
    width: '100%',
    height: '100%',
  },
  levelFilter: {
    marginBottom: 10,
  },
  effectFilter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  spellContainer: {
    width: '80%',
    marginTop: 20,
  },
  spellItem: {
    backgroundColor: '#333',
    padding: 15,
    marginVertical: 10,
    borderRadius: 10,
    borderColor: '#7F7F7F',
    borderWidth: 1.5,
  },
  spellName: {
    fontSize: 18,
    color: '#d6d6d6',
  },
  spellDetails: {
    color: '#a1a1a1',
  },
  noResultsText: {
    textAlign: 'center',
    color: '#d6d6d6',
    fontSize: 18,
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  backButton: {
    width: '20%',
    borderColor: '#7F7F7F',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
    marginTop: 10,
    padding: 10,
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  backButtonText: {
    color: '#d6d6d6',
  },
  sectionContainer: {
    width: '80%',
    alignItems: 'center',
  },
  itemText: {
    color: 'white',
    fontSize: 16,
    borderColor: '#7F7F7F',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
    marginVertical: 5,
    padding: 5,
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  characterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  characterImage: {
    width: 100,
    height: 100,
    margin: 10,
    justifyContent: 'flex-end',
  },
  buttonContainerCamp: {
    flex: 1,
    width: '80%',
    marginBottom: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderColor: '#7F7F7F',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  buttonTextPlus: {
    color: 'green',
    justifyContent: 'center',
    textAlign: 'center',
    padding: 8,
  },
  deleteButton: {
    padding: 7,
    marginLeft: 10,
    justifyContent: 'space-between',
    borderColor: '#7F7F7F',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
    backgroundColor: 'rgba(255, 0, 0, 0.8)',
  },
  deleteButtonText: {
    color: '#d6d6d6',
  },
  addCampaignContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});

export default styles;